import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { cn } from "@/lib/utils";
import { AppSidebar } from "@/components/Dashboard/Sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { DashboardHeader } from "@/components/Dashboard/DashboardHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${cn({ "debug-screens": process.env.NODE_ENV === "development" })}    bg]`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full ">
            <SidebarTrigger />
            <DashboardHeader/>
            <div className= " ml-[20%]  2xl:ml-[30%] ">
              {children}

            </div>

          </main>

        </SidebarProvider>

      </body>
    </html>
  );
}
